package com.contextsolutions.mobileagent.ui.branding

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.painter.Painter

/**
 * The app brand mark (the launcher icon — a white speech bubble on a dark-navy
 * plate) shown in the chat top bar. Bundled per-platform: Compose Resources do
 * NOT package into the AGP-9 `com.android.kotlin.multiplatform.library` variant
 * (the asset-copy task's `outputDirectory` is never wired, so the PNG compiles
 * into accessors but is absent from the APK → a runtime `MissingResourceException`),
 * so this rides the same expect/actual seam as the other platform UI bits
 * (`PlatformMarkdownMath`, `isDesktopPlatform`): an Android drawable
 * (`drawable-nodpi/app_logo.png`, merged via the AAR) and a desktop classpath
 * resource (`app_logo.png`). Regenerated by `desktopApp/icons/generate_icons.py`.
 */
@Composable
expect fun appLogoPainter(): Painter
